---
# tenant
apiVersion: tsb.tetrate.io/v2
kind: Tenant
metadata:
  name: tier1
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  displayName: Tier1
---
# tenant settings
apiVersion: tsb.tetrate.io/v2
kind: TenantSetting
metadata:
  name: tier1-tenant-setting
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: tier1
spec:
  defaultSecuritySetting:
    authenticationSettings:
      trafficMode: REQUIRED
---
# workspaces
apiVersion: tsb.tetrate.io/v2
kind: Workspace
metadata:
  name: tier1
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: tier1
spec:
  displayName: Tier1
  namespaceSelector:
    names:
      - "t1/tier1"
---
# gateway group
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: tier1-gateway-group
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: tier1
    tsb.tetrate.io/workspace: tier1
spec:
  displayName: Tier1 Gateway Group
  namespaceSelector:
    names:
      - "t1/tier1"
  configMode: BRIDGED
---
# gateway deploy
apiVersion: gateway.tsb.tetrate.io/v2
kind: Gateway
metadata:
  name: tier1-gateway
  namespace: tier1
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: tier1
    tsb.tetrate.io/workspace: tier1
    tsb.tetrate.io/gatewayGroup: tier1-gateway-group
spec:
  workloadSelector:
    namespace: tier1
    labels:
      app: tier1-gateway
  http:
  - hostname: bookinfo.tetrate.io
    name: bookinfo
    port: 80
    routing:
      rules:
        - route:
            clusterDestination:
              clusters:
                - name: c1
                  weight: 50
                - name: c2
                  weight: 50
