apiVersion: v1
kind: Service
metadata:
  labels:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: tsb
  name: tsb-es-http-lb
  namespace: elastic
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: tsb
  sessionAffinity: None
  type: LoadBalancer
